/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istlbd.gui;

/**
 *
 * @author Maverick
 */
public class PersonalInfoForm extends javax.swing.JPanel {

    /**
     * Creates new form PersonalInfoForm
     */
    public PersonalInfoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personal_info_enr_scrollpane = new javax.swing.JScrollPane();
        personal_information_enrollment_panel = new javax.swing.JPanel();
        pi_label_first_name = new javax.swing.JLabel();
        pi_value_first_name = new javax.swing.JTextField();
        pi_label_last_name = new javax.swing.JLabel();
        pi_value_last_name = new javax.swing.JTextField();
        pi_value_given_name = new javax.swing.JTextField();
        pi_label_given_name = new javax.swing.JLabel();
        pi_label_nick_name = new javax.swing.JLabel();
        pi_value_nick_name = new javax.swing.JTextField();
        pi_label_father_name = new javax.swing.JLabel();
        pi_value_father_name = new javax.swing.JTextField();
        pi_value_mother_name = new javax.swing.JTextField();
        pi_label_mother_name = new javax.swing.JLabel();
        pi_value_spouse_name = new javax.swing.JTextField();
        pi_label_spouse_name = new javax.swing.JLabel();
        pi_label_gender = new javax.swing.JLabel();
        pi_value_dob = new javax.swing.JTextField();
        pi_label_dob = new javax.swing.JLabel();
        pi_value_nid = new javax.swing.JTextField();
        pi_label_nid = new javax.swing.JLabel();
        pi_label_blood_grp = new javax.swing.JLabel();
        pi_value_gender = new javax.swing.JComboBox();
        pi_value_blood_grp = new javax.swing.JComboBox();
        pi_value_telephone = new javax.swing.JTextField();
        pi_label_tel_no = new javax.swing.JLabel();
        pi_label_email = new javax.swing.JLabel();
        pi_value_email = new javax.swing.JTextField();
        pi_value_driving_license = new javax.swing.JTextField();
        pi_label_driving_license = new javax.swing.JLabel();
        pi_label_organization_name = new javax.swing.JLabel();
        pi_label_business_type = new javax.swing.JLabel();
        pi_label_profession = new javax.swing.JLabel();
        pi_value_business_type = new javax.swing.JTextField();
        pi_value_org_name = new javax.swing.JTextField();
        pi_label_present_add = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        pi_value_present_address = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        pi_value_perm_add = new javax.swing.JTextArea();
        pi_label_permanent_add = new javax.swing.JLabel();
        pi_value_profession = new javax.swing.JComboBox();
        pi_value_race = new javax.swing.JComboBox();
        pi_label_race = new javax.swing.JLabel();
        pi_value_ethnicity = new javax.swing.JComboBox();
        pi_label_ethnicity = new javax.swing.JLabel();
        pi_label_eye_clr_l = new javax.swing.JLabel();
        pi_value_eye_clr_l = new javax.swing.JComboBox();
        pi_label_eye_clr_r = new javax.swing.JLabel();
        pi_value_eye_clr_r = new javax.swing.JComboBox();
        pi_label_hair_color_org = new javax.swing.JLabel();
        pi_value_hair_clr_org = new javax.swing.JComboBox();
        pi_value_hair_clr_arti = new javax.swing.JComboBox();
        pi_label_hair_clr_arti = new javax.swing.JLabel();
        pi_label_hair_build = new javax.swing.JLabel();
        pi_value_hair_build = new javax.swing.JComboBox();
        pi_value_disability = new javax.swing.JComboBox();
        pi_label_disability = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        pi_value_others = new javax.swing.JTextArea();
        pi_label_others = new javax.swing.JLabel();
        pi_value_nationality = new javax.swing.JComboBox();
        pi_label_nationality = new javax.swing.JLabel();

        personal_info_enr_scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        personal_information_enrollment_panel.setPreferredSize(new java.awt.Dimension(847, 750));

        pi_label_first_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_first_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_first_name.setText("FIRST NAME");

        pi_label_last_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_last_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_last_name.setText("LAST NAME");

        pi_label_given_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_given_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_given_name.setText("GIVEN NAME");

        pi_label_nick_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_nick_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_nick_name.setText("NICK NAME");

        pi_label_father_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_father_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_father_name.setText("FATHER NAME");

        pi_label_mother_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_mother_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_mother_name.setText("MOTHER NAME");

        pi_label_spouse_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_spouse_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_spouse_name.setText("SPOUSE NAME");

        pi_label_gender.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_gender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_gender.setText("GENDER");

        pi_label_dob.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_dob.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_dob.setText("DATE OF BIRTH");

        pi_label_nid.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_nid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_nid.setText("NATIONAL ID");

        pi_label_blood_grp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_blood_grp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_blood_grp.setText("BLOOD TYPE");

        pi_value_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", "THIRD GENDER" }));

        pi_value_blood_grp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        pi_label_tel_no.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_tel_no.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_tel_no.setText("TELEPHONE");

        pi_label_email.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_email.setText("EMAIL");

        pi_label_driving_license.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_driving_license.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_driving_license.setText("DRIVING LICENSE");

        pi_label_organization_name.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_organization_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_organization_name.setText("ORGANIZATION / OFFICE NAME");

        pi_label_business_type.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_business_type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_business_type.setText("BUSINESS TYPE");

        pi_label_profession.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_profession.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_profession.setText("PROFESSION");

        pi_label_present_add.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_present_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_present_add.setText("PRESENT ADDRESS");

        pi_value_present_address.setColumns(20);
        pi_value_present_address.setRows(5);
        jScrollPane7.setViewportView(pi_value_present_address);

        pi_value_perm_add.setColumns(20);
        pi_value_perm_add.setRows(5);
        jScrollPane8.setViewportView(pi_value_perm_add);

        pi_label_permanent_add.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_permanent_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_permanent_add.setText("PERMANENT ADDRESS");

        pi_value_profession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROFESSION" }));

        pi_value_race.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RACE" }));

        pi_label_race.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_race.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_race.setText("RACE");

        pi_value_ethnicity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ETHNICITY" }));

        pi_label_ethnicity.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_ethnicity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_ethnicity.setText("ETHNICITY");

        pi_label_eye_clr_l.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_eye_clr_l.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_eye_clr_l.setText("EYE COLOR (LEFT)");

        pi_value_eye_clr_l.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EYE COLOR LEFT" }));

        pi_label_eye_clr_r.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_eye_clr_r.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_eye_clr_r.setText("EYE COLOR (RIGHT)");

        pi_value_eye_clr_r.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EYE COLOR RIGHT" }));

        pi_label_hair_color_org.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_hair_color_org.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_hair_color_org.setText("HAIR COLOR (ORIGINAL)");

        pi_value_hair_clr_org.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ORIGINAL HAIR COLOR" }));

        pi_value_hair_clr_arti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARTIFICIAL HAIR COLOR" }));

        pi_label_hair_clr_arti.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_hair_clr_arti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_hair_clr_arti.setText("HAIR COLOR (ARTIFICIAL)");

        pi_label_hair_build.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_hair_build.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_hair_build.setText("HAIR BUILD");

        pi_value_hair_build.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HAIR BUILD" }));

        pi_value_disability.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DISABILITY" }));

        pi_label_disability.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_disability.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_disability.setText("DISABILITY");

        pi_value_others.setColumns(20);
        pi_value_others.setRows(5);
        jScrollPane9.setViewportView(pi_value_others);

        pi_label_others.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_others.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_others.setText("OTHERS");

        pi_value_nationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BANGLADESHI" }));

        pi_label_nationality.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pi_label_nationality.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pi_label_nationality.setText("NATIONALITY");

        javax.swing.GroupLayout personal_information_enrollment_panelLayout = new javax.swing.GroupLayout(personal_information_enrollment_panel);
        personal_information_enrollment_panel.setLayout(personal_information_enrollment_panelLayout);
        personal_information_enrollment_panelLayout.setHorizontalGroup(
            personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pi_label_present_add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_profession, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_given_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_given_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_nick_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_nick_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_spouse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_spouse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_blood_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_blood_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                                .addComponent(pi_label_business_type, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86)
                                                .addComponent(pi_label_organization_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pi_label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pi_value_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pi_label_driving_license, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pi_value_driving_license, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pi_label_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pi_value_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pi_label_others, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_value_hair_clr_org, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_hair_color_org, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_value_hair_clr_arti, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_hair_clr_arti))
                                .addGap(27, 27, 27)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_hair_build, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_hair_build, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_disability, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_disability, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addComponent(pi_value_profession, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pi_value_business_type, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(pi_value_org_name, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pi_label_permanent_add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8)
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_race, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_race, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_eye_clr_l, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_eye_clr_l, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi_label_eye_clr_r, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_eye_clr_r, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        personal_information_enrollment_panelLayout.setVerticalGroup(
            personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_nick_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_nick_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_given_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_given_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_spouse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_spouse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                    .addComponent(pi_label_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pi_value_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                    .addComponent(pi_label_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pi_value_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pi_label_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_label_blood_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pi_value_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pi_value_blood_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addComponent(pi_label_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pi_value_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addComponent(pi_label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pi_value_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addComponent(pi_label_driving_license, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pi_value_driving_license, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pi_label_profession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pi_label_business_type, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pi_label_organization_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pi_value_business_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pi_value_profession, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pi_value_org_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pi_label_present_add, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_permanent_add, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pi_label_race, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pi_value_race, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(pi_label_eye_clr_l, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pi_value_eye_clr_l, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_eye_clr_r, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_eye_clr_r, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personal_information_enrollment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                            .addComponent(pi_label_hair_color_org, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pi_value_hair_clr_org, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                            .addComponent(pi_label_hair_build, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pi_value_hair_build, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_hair_clr_arti, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_hair_clr_arti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personal_information_enrollment_panelLayout.createSequentialGroup()
                        .addComponent(pi_label_disability, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi_value_disability, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pi_label_others, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        personal_info_enr_scrollpane.setViewportView(personal_information_enrollment_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personal_info_enr_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personal_info_enr_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane personal_info_enr_scrollpane;
    private javax.swing.JPanel personal_information_enrollment_panel;
    private javax.swing.JLabel pi_label_blood_grp;
    private javax.swing.JLabel pi_label_business_type;
    private javax.swing.JLabel pi_label_disability;
    private javax.swing.JLabel pi_label_dob;
    private javax.swing.JLabel pi_label_driving_license;
    private javax.swing.JLabel pi_label_email;
    private javax.swing.JLabel pi_label_ethnicity;
    private javax.swing.JLabel pi_label_eye_clr_l;
    private javax.swing.JLabel pi_label_eye_clr_r;
    private javax.swing.JLabel pi_label_father_name;
    private javax.swing.JLabel pi_label_first_name;
    private javax.swing.JLabel pi_label_gender;
    private javax.swing.JLabel pi_label_given_name;
    private javax.swing.JLabel pi_label_hair_build;
    private javax.swing.JLabel pi_label_hair_clr_arti;
    private javax.swing.JLabel pi_label_hair_color_org;
    private javax.swing.JLabel pi_label_last_name;
    private javax.swing.JLabel pi_label_mother_name;
    private javax.swing.JLabel pi_label_nationality;
    private javax.swing.JLabel pi_label_nick_name;
    private javax.swing.JLabel pi_label_nid;
    private javax.swing.JLabel pi_label_organization_name;
    private javax.swing.JLabel pi_label_others;
    private javax.swing.JLabel pi_label_permanent_add;
    private javax.swing.JLabel pi_label_present_add;
    private javax.swing.JLabel pi_label_profession;
    private javax.swing.JLabel pi_label_race;
    private javax.swing.JLabel pi_label_spouse_name;
    private javax.swing.JLabel pi_label_tel_no;
    private javax.swing.JComboBox pi_value_blood_grp;
    private javax.swing.JTextField pi_value_business_type;
    private javax.swing.JComboBox pi_value_disability;
    private javax.swing.JTextField pi_value_dob;
    private javax.swing.JTextField pi_value_driving_license;
    private javax.swing.JTextField pi_value_email;
    private javax.swing.JComboBox pi_value_ethnicity;
    private javax.swing.JComboBox pi_value_eye_clr_l;
    private javax.swing.JComboBox pi_value_eye_clr_r;
    private javax.swing.JTextField pi_value_father_name;
    private javax.swing.JTextField pi_value_first_name;
    private javax.swing.JComboBox pi_value_gender;
    private javax.swing.JTextField pi_value_given_name;
    private javax.swing.JComboBox pi_value_hair_build;
    private javax.swing.JComboBox pi_value_hair_clr_arti;
    private javax.swing.JComboBox pi_value_hair_clr_org;
    private javax.swing.JTextField pi_value_last_name;
    private javax.swing.JTextField pi_value_mother_name;
    private javax.swing.JComboBox pi_value_nationality;
    private javax.swing.JTextField pi_value_nick_name;
    private javax.swing.JTextField pi_value_nid;
    private javax.swing.JTextField pi_value_org_name;
    private javax.swing.JTextArea pi_value_others;
    private javax.swing.JTextArea pi_value_perm_add;
    private javax.swing.JTextArea pi_value_present_address;
    private javax.swing.JComboBox pi_value_profession;
    private javax.swing.JComboBox pi_value_race;
    private javax.swing.JTextField pi_value_spouse_name;
    private javax.swing.JTextField pi_value_telephone;
    // End of variables declaration//GEN-END:variables
}
